### ISSUE TITLE
/etc/shadow: root password left unlocked

### ISSUE THREAD

**Issue by jku** [alpinelinux/alpine-make-rootfs#11]
The "official" Alpine container rootfs's have their root password locked in /etc/shadow (see https://git.alpinelinux.org/aports/tree/scripts/genrootfs.sh#n44). I think that might be a reasonable choice for alpine-make-rootfs as well: this is one of the very few differences between those two.

**Comment by derekmceachern** [comment]
This seems like a pretty straight forward change and reasonable request. @jirutka is this something you would consider merging?

**Comment by jirutka** [comment]
Yes. Tbh, I don’t remember why I left it as is.

**Comment by derekmceachern** [comment]
Ok, I've opened the pr. I just added the change and didn't make it a configurable option or update the readme with the new hash.

**Comment by jirutka** [comment]
This has been fixed in #20.

**Comment by inklesspen** [comment]
This fix seems to have broken the `--no-default-pkgs` feature; it does not gracefully handle the case where /etc/shadow doesn't exist.

(FWIW, I'm not trying to make a _working_ rootfs; I'm just trying to automate downloading a few packages and combining them into a tarball.)
