### ISSUE TITLE
Add fsfreeze to the busybox build?

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [alpinelinux/alpine-make-rootfs#23]
This tool is useful for backup because it will halt any filesystem operation, so we can resume service quickly after say like velero backup finished. I know the right way is to use an immutable data structure that we can copy at any point in time but for some adhoc services such as Gitea we have no choice

**Comment by jirutka** [comment]
How is this related to `alpine-make-rootfs`? If you want to install `fsfreezer` to your rootfs, just install it: `alpine-make-rootfs ... --packages cmd:fsfreezer`.
